### ISSUE TITLE
scheduled workflow job

### ISSUE THREAD

**Issue by Kevmo92** [CircleCI-Public/circleci-demo-workflows#19]
I have a yaml file that looks like this:

```yaml
version: 2.0
anchors:
  - &container_config
    docker:
      - image: docker:stable
    resource_class: small
    working_directory: /root/checkout
jobs:
  build:
    <<: *container_config
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Simple build command
        command: command
  scheduled_build:
    <<: *container_config
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: simple command
        command: command
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 12 ? * 5"
          filters:
            branches:
              only: release
    jobs:
      - scheduled_build
```

But whenever this is pushed to github, circleci doesn't even see the commit and doesn't build anything. Removing the triggers section I'm able to build as normal.

It's likely a syntax issue, but it's odd that circleci isn't even seeing the commits anymore. Usually the build would fail saying there is a syntax issue with the yaml file. 

documentation on [triggers](https://circleci.com/docs/2.0/configuration-reference/#triggers )  & [schedule](https://circleci.com/docs/2.0/configuration-reference/#schedule)
